version: "3.8"
services:
  api_chess:
    build:
      context: ./api/chess
    networks:
      netopia:
        aliases:
          - api_chess
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      netopia:
        aliases:
          - nginx
networks:
  netopia:
    driver: bridge
